pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 DipLatex.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 fourier.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 genarticle.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 genbook.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 genbook11.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 genminimal.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 genreport.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 genamsart.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 gensuftesi.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamsbsy.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamsfonts.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamsgen.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamsmath.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamsopn.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamssymb.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 MamssymbVamsfont.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamstext.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamscd.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mamsxtra.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 MbabelVFixLtXHyph.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mappendix.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Marray.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mbeamer.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mbooktabs.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mccaption.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mchangepage.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mchngntr.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mchngpage.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 mcmap.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mcolor.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 McolorVxcolor.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mcrop.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 mfontec.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mfourier.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mgeometry.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mgraphics.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mgraphicx.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Minputenc.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Minputenc1.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Minputenc2.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Misomath.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mmemoir.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mmemoire.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mmicrotype.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mnabal1.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mtextcomp.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Mxcolor.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 MxcolorVcolor.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 MxcolorVcrop.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18 Nfixltx2e.tex
pdflatex.exe -synctex=1 -interaction=nonstopmode --enable-write18  Mamsthm.tex